### PR TITLE
Added (initial) schema.org mappings of module types

### PR DESCRIPTION
**Pull request by egonw**
Which can be used to update/extend https://github.com/libscie/ResearchEquals.com/pull/322

### CODE REVIEW

**Comment by chartgerink** [comment]
Thanks @egonw for this PR 👍 

You added the `schema` mappings to the seeding script; next step is to add the `schema` to the `ModuleType` table.
 
How does it sound to you if I add `schema` to the `ModuleType` table as a required string that defaults to `CreativeWork`? In other words, any new `ModuleType` will default to `CreativeWork` but can be specified as something else.

**Comment by egonw** [comment]
Sounds reasonable to me! Feel free to redo what I did... it's just to get the ball rolling :)

**Comment by chartgerink** [comment]
No need to redo your work - it's perfect 😊 I'll add a database migration in the morning.

**Comment by chartgerink** [comment]
Superceded by #331 which includes the database migration. The original contributions from this PR are included 😊

**Pull request closed without merging**
