### PR TITLE
Removing section grid template on wider screen

### LINKED ISSUE #1986: Visual bug Collections modal🐛
### URL of the Page

_No response_

### What happened?

Screenshot 2024-03-01 at 10 26 13

### Steps to reproduce

_No response_

### What browser(s) did you use?

Firefox

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jazellemaira**
This PR fixes the visual bug reported in issue #1986 
Collections-modal-screenshot
Fixes #1986

### CODE REVIEW

**Comment by chartgerink** [comment]
Thanks @jazellemaira for proposing this change! Appreciate you taking the time to contribute here 😊 

The current changes will change the designs. Your change makes it one column, two rows. The original design is two columns, one row. This is not very clear from #1986 - sorry for the lack of context.

The fix should end up looking something like this:

Screenshot 2024-03-03 at 11 12 34

I looked into it and it seems like there is a `sm:min-w-120` that is causing the issue in a parent div. Do you want to take another pass at this?

**Review by chartgerink — CHANGES_REQUESTED** [review]
Thanks @jazellemaira for proposing this change! Appreciate you taking the time to contribute here 😊 

The current changes will change the designs. Your change makes it one column, two rows. The original design is two columns, one row. This is not very clear from #1986 - sorry for the lack of context.

The fix should end up looking something like this:

Screenshot 2024-03-03 at 11 12 34

I looked into it and it seems like there is a `sm:min-w-120` that is causing the issue in a parent div. Do you want to take another pass at this?

**Comment by jazellemaira** [comment]
Hi @chartgerink. Thank you for telling me about the design. I looked into it further and found that it is not `sm:min-w-120` that was causing the issue to the parent div but rather the 'sm:max-w-120'. I made some changes and now it's two columns, one row as per design. 

Corrected-collections-modal-screenshot

**Review by chartgerink — APPROVED** [review]
Perfect, thanks a lot @jazellemaira 🙏 Merging your first contribution to ResearchEquals in 3-2-1... 😄

**Comment by chartgerink** [comment]
@all-contributors add @jazellemaira for code

**Pull request merged**
