### PR TITLE
Use a state for the editor role to sync the dropdown with what's actually selected

### LINKED ISSUE #742: Users can select collections roles that are not allowed in the drop-down 🐛
### URL of the Page

https://www.researchequals.com/collections/waca-fd/admin

### What happened?

Currently, the user can select a role that's not allowed in the collections' admin panel in the drop-down menu. (Just visually)

For example, in my personal collection's admin page, I can select myself as a USER.

image

It's not allowed, and thus it will throw a snack bar at the bottom with an error message:

image

But then, the selection in the drop-down is now changed to USER. Ideally, we want to fix it to OWNER in this case.

image

### Steps to reproduce

1. Go to your personal collections' admin panel
2. Try to change your role to USER

### What browser(s) did you use?

Chrome

### Anything else?

This issue came up during the review for the collections PR https://github.com/libscie/ResearchEquals.com/pull/685#discussion_r977799858

### PR DESCRIPTION
**Pull request by nsunami**
This PR uses a state for the editor role, so that the selection would correspond to what's allowed in the backend. Fixes #742.

(I'm making this PR a draft since I'm yet to test the collaborative and community collection. Researching about Stripe.)

### CODE REVIEW

**Comment by nsunami** [comment]
Now that I can test Stripe on local (#721), I can test for the other types of collections.

**Comment by nsunami** [comment]
While testing this, I realized that I could not change the collections roles. https://github.com/libscie/ResearchEquals.com/issues/765 
And thus I cannot proceed with testing. I think it would make sense to address #765 first before merging this PR.

**Comment by nsunami** [comment]
Now that #765 is closed, I'm making this PR ready for review! (If merge with main is needed, we can do that too, since this branch may be behind the main a bit...)

**Comment by chartgerink** [comment]
@nsunami it looks like there are no conflicts - would you like me to review?

**Comment by nsunami** [comment]
@chartgerink Yes please! Thanks for checking 🙏

**Review by chartgerink — APPROVED** [review]
I know this one has been the cause of some friction and stress, and I'm glad we didn't rush this tuesday - that was a good decision of you. 🙌 

Thanks for pulling this along - the pleasure is yours to merge this 😊

**Pull request merged**
