### PR TITLE
Update the `faker` seeding script

### LINKED ISSUE #621: Faker deprecation update
The `faker` library is deprecating one of the functions in the next major release according to logs:

```
[@faker-js/faker]: faker.name.findName() is deprecated since v7.4 and will be removed in v8.0. 
Please use faker.name.fullName() instead..
```

Fixing this before then would be an easy but good idea! 🙌

### PR DESCRIPTION
**Pull request by nsunami**
This PR updates the `faker` seeding script for the test data, since the `faker` package is deprecating the function we are using (`faker.name.findName()`). I updated the script a bit so that we will get fake first names for the `firstName` field, and fake last name for the `lastName` field.

Fixes #621 

image

-----
On a side note, I noticed that the avatar image does not correspond to the handle. I realized that this is an expected behavior given that the seeding script is generating `avatar` independent of the handle:

```js
avatar: `https://eu.ui-avatars.com/api/?rounded=true&background=574cfa&color=ffffff&name=${faker.internet.userName()}`,
```

### CODE REVIEW

**Comment by nsunami** [comment]
Note that it may make sense to test this after we add the seeding script for Heroku (After #724)

**Comment by nsunami** [comment]
Now that #724 is merged, I'm marking this ready for review ✌️

**Review by chartgerink — APPROVED** [review]
Straightforward and important fix, thanks 🙏

**Comment by nsunami** [comment]
Natuurlijk! 👍

**Pull request merged**
