### PR TITLE
Update drafts

### PR DESCRIPTION
**Pull request by chartgerink**
This PR updates the drafts page to the new designs. Work in progress, pushing to not lose any local work.

This includes a complete rework of the "inbox" style display - there were some issues using HeadlessUI's disclosure on iOS - the display of the buttons was funky. 

Screenshot 2021-12-25 at 12 07 50

## Todo

- [x] Edit module
- [x] Publish module (see also #28 and #161 to complete those)
~~- [ ] Follows from linking~~
- [x] Manage authors

### CODE REVIEW

**Comment by chartgerink** [comment]
Now with improved author management 
Screenshot 2021-12-28 at 14 39 09

**Comment by chartgerink** [comment]
Editing is in a semi better place - now at least in the same location as the regular metadata but still requires styling.

Screenshot 2021-12-28 at 14 51 16

**Comment by psobrakseaton** [comment]
> Editing is in a semi better place - now at least in the same location as the regular metadata but still requires styling.
> 
> Screenshot 2021-12-28 at 14 51 16

This is really good. I have had some ideas over Christmas as to make this smoothed out, but this is a step in the right direction.

**Comment by chartgerink** [comment]
Now with publishing action (still requires #161 and #28 to be finalized).

Screenshot 2021-12-28 at 15 30 52

The modal that comes from it is unstyled at the moment.

Screenshot 2021-12-28 at 15 33 23

**Comment by chartgerink** [comment]
Note: Depends on #167 before merging.

**Pull request merged**
